import { useEffect, useMemo, useState } from 'react';
import ReactFlow, { Background, BackgroundVariant, Controls, Handle, Position, useEdgesState, useNodesState, type Edge, type Node, type NodeProps } from 'reactflow';
import { CheckCircle2, Database, Download, FileText, LoaderCircle, Network, RotateCcw, Shield, X } from 'lucide-react';
import { agentResults, type AgentResult } from './data/agentResults';
import { fetchAgentAnalysisResults, type AgentAnalysisResponse } from './data/agentAnalysisApi';
import { AgentSummaryPage } from '../summary/AgentSummaryPage';

interface Props { onClose: () => void }
interface CaseNodeData { onSelect: () => void }
interface AgentNodeData { result: AgentResult; selected: boolean; onSelect: (result: AgentResult) => void }

function CaseDataNode({ data }: NodeProps<CaseNodeData>) { return <div className="aad-case-node" onClick={data.onSelect}><Handle type="source" position={Position.Bottom} className="!h-2 !w-2 !border-0 !bg-gray-300" /><div className="aad-case-data-icon"><Database size={24} /></div><b>CASE DATA</b><span>Case #8402</span><small>Shared with 10 agents</small></div>; }
function AgentNode({ data }: NodeProps<AgentNodeData>) { const { result } = data; return <div className={`aad-agent-node ${data.selected ? 'selected' : ''}`} style={{ '--agent-color': result.color } as React.CSSProperties} onClick={() => data.onSelect(result)}><Handle type="target" position={Position.Top} className="!h-2 !w-2 !border-0 !bg-gray-300" /><div className="aad-node-icon"><img src={result.imageUrl} alt={`${result.domain} portrait`} /></div><div className="aad-node-copy"><b>{result.name}</b><span>{result.domain}</span></div><CheckCircle2 size={15} className="aad-node-check" /></div>; }
const nodeTypes = { caseNode: CaseDataNode, agentNode: AgentNode };

interface ProcessingViewProps { results: AgentResult[]; nodes: Node[]; edges: Edge[]; revealedAgents: number; loadingProgress: number }
function ProcessingView({ results, nodes, edges, revealedAgents, loadingProgress }: ProcessingViewProps) {
  const activeAgent = results[Math.min(revealedAgents, results.length - 1)];
  const visibleNodes = nodes;
  const visibleEdges = edges;
  const agentMessage = activeAgent.domain.toLowerCase().includes('financial') ? 'I am investigating financial records and money transfers.' : activeAgent.domain.toLowerCase().includes('telecom') ? 'I am investigating calls, devices, and network links.' : activeAgent.domain.toLowerCase().includes('forensic') ? 'I am investigating digital evidence and recovered artifacts.' : activeAgent.domain.toLowerCase().includes('prosecutor') ? 'I am investigating evidence strength and proof gaps.' : activeAgent.domain.toLowerCase().includes('defense') ? 'I am investigating alternative explanations and challenges.' : activeAgent.domain.toLowerCase().includes('chronologist') ? 'I am investigating the order of events and timestamps.' : activeAgent.domain.toLowerCase().includes('judge') ? 'I am investigating the strongest supported conclusion.' : activeAgent.domain.toLowerCase().includes('auditor') ? 'I am investigating evidence integrity and claim validation.' : activeAgent.domain.toLowerCase().includes('intelligence') ? 'I am investigating people, links, and the wider network.' : 'I am investigating the case theory and key leads.';
  useEffect(() => { document.documentElement.style.setProperty('--aad-bubble-text', JSON.stringify(agentMessage)); return () => { document.documentElement.style.removeProperty('--aad-bubble-text'); }; }, [agentMessage]);
  const stage = revealedAgents === results.length ? 'Building the final investigation summary' : revealedAgents === 0 ? 'Reading case data and evidence sources' : `Processing ${activeAgent.name}`;
  const characterImage = activeAgent.id === '01' ? '/images/CBI.png' : activeAgent.id === '02' ? '/images/fieldinvest.png' : activeAgent.id === '03' ? '/images/cyber.png' : activeAgent.id === '04' ? '/images/finance.png' : activeAgent.id === '05' ? '/images/telecom.png' : activeAgent.id === '06' ? '/images/socialmedia.png' : activeAgent.id === '07' ? '/images/law.png' : activeAgent.id === '08' ? '/images/police.png' : activeAgent.id === '09' ? '/images/kyc.png' : activeAgent.id === '10' ? '/images/10thagent.png' : activeAgent.imageUrl;
  return <section className="aad-shell"><div className="aad-toolbar"><div><Network size={17} /><b>Agent Analysis</b><span>Case #8402 · Case Data → Agent Results</span></div><div><span className="aad-live"><i />Agents processing</span></div></div><div className="aad-layout"><main className="aad-canvas"><div className="aad-canvas-label">Case data distributed to each agent · processing live</div><ReactFlow nodes={visibleNodes} edges={visibleEdges} nodeTypes={nodeTypes} fitView fitViewOptions={{ padding: 0.15 }} minZoom={0.45} maxZoom={2} proOptions={{ hideAttribution: true }}><Background variant={BackgroundVariant.Dots} gap={20} size={1.5} color="#cbd5df" /><Controls showInteractive={false} /></ReactFlow><div className="aad-canvas-footer"><LoaderCircle size={13} /> {stage}<span>Agent avatars are joining the canvas</span></div></main><aside className="aad-detail aad-processing-panel"><div className="aad-processing-head"><small>LIVE AGENT PROCESSING</small><h2>{activeAgent.name}</h2><span>{activeAgent.domain}</span></div><div className="aad-character-stage" style={{ '--agent-color': activeAgent.color } as React.CSSProperties}><img src={characterImage} alt={`${activeAgent.name} avatar`} /><div className="aad-character-glow" /></div><div className="aad-processing-status"><LoaderCircle size={13} /> Analyzing case evidence</div><div className="aad-agent-timeline" aria-label="Agent processing timeline">{results.map((agent, index) => { const complete = index < revealedAgents; const current = index === revealedAgents && revealedAgents < results.length; return <div className={`aad-timeline-agent ${complete ? 'complete' : ''} ${current ? 'current' : ''}`} key={agent.id}><div className="aad-timeline-avatar" style={{ '--agent-color': agent.color } as React.CSSProperties}>{complete || current ? <img src={agent.imageUrl} alt={`${agent.name} avatar`} /> : null}{complete && <CheckCircle2 size={12} />}</div></div>; })}</div></aside></div></section>;
}

export function AgentAnalysisDemo({ onClose }: Props) {
  const [ready, setReady] = useState(false); const [selected, setSelected] = useState<AgentResult | null>(null); const [analysis, setAnalysis] = useState<AgentAnalysisResponse | null>(null); const [summaryOpen, setSummaryOpen] = useState(false); const [revealedAgents, setRevealedAgents] = useState(0);
  useEffect(() => { let active = true; fetchAgentAnalysisResults().then((data) => { if (active) setAnalysis(data); }); return () => { active = false; }; }, []);
  const results = analysis?.agents ?? agentResults;
  useEffect(() => { if (ready || results.length === 0) return; if (revealedAgents < results.length) { const revealTimer = window.setTimeout(() => setRevealedAgents((value) => Math.min(value + 1, results.length)), 1800); return () => window.clearTimeout(revealTimer); } const summaryTimer = window.setTimeout(() => { setReady(true); setSummaryOpen(true); }, 1400); return () => window.clearTimeout(summaryTimer); }, [ready, revealedAgents, results.length]);
  const loadingProgress = results.length ? Math.round((revealedAgents / results.length) * 100) : 0;
  const downloadSummary = (agent: AgentResult) => { const report = [`AEGIS AGENT ANALYSIS`, `Case #8402 — Operation Shadow Network`, ``, `${agent.id} — ${agent.name}`, `Domain: ${agent.domain}`, `Confidence: ${agent.confidence}%`, ``, `GENERATED SUMMARY`, agent.findings[0], ``, `KEY FINDINGS`, ...agent.findings.map((finding) => `• ${finding}`), ``, `LINKED CASE DATA`, ...agent.links.map((link) => `• ${link}`)].join('\n'); const url = URL.createObjectURL(new Blob([report], { type: 'text/plain;charset=utf-8' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `case-8402-agent-${agent.id}-summary.txt`; anchor.click(); URL.revokeObjectURL(url); };
  const initialNodes = useMemo<Node[]>(() => [{ id: 'case', type: 'caseNode', position: { x: 480, y: 280 }, data: { onSelect: () => setSelected(null) } }, ...results.map((result, index) => ({ id: result.id, type: 'agentNode', position: [{ x: 40, y: 30 }, { x: 340, y: 20 }, { x: 650, y: 30 }, { x: 750, y: 210 }, { x: 690, y: 430 }, { x: 400, y: 490 }, { x: 90, y: 430 }, { x: 0, y: 210 }, { x: 130, y: 125 }, { x: 450, y: 125 }][index], data: { result, selected: false, onSelect: setSelected } }))], [results]);
  const initialEdges = useMemo<Edge[]>(() => results.map((result) => ({ id: `case-${result.id}`, source: 'case', target: result.id, type: 'default', animated: true, style: { stroke: result.color, strokeWidth: 1.4, strokeDasharray: '2 5' } })), [results]);
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes); const [edges, , onEdgesChange] = useEdgesState(initialEdges);
  const onNodeClick = (_event: React.MouseEvent, node: Node) => { const result = results.find((item) => item.id === node.id); if (result) { setSelected(result); setNodes((current) => current.map((item) => ({ ...item, data: { ...item.data, selected: item.id === result.id } }))); } };
  if (!ready) return <ProcessingView results={results} nodes={nodes} edges={edges} revealedAgents={revealedAgents} loadingProgress={loadingProgress} />;
  if (summaryOpen && analysis) return <AgentSummaryPage analysis={analysis} onBack={() => setSummaryOpen(false)} onClose={onClose} />;
  return <section className="aad-shell"><div className="aad-toolbar"><div><Network size={17} /><b>Agent Analysis</b><span>Case #8402 · Case Data → Agent Results</span></div><div><span className="aad-live"><i />10 agents completed</span><button onClick={() => setNodes(initialNodes)}><RotateCcw size={14} /> Reset layout</button><button onClick={onClose} aria-label="Close Agent Analysis"><X size={17} /></button></div></div><div className="aad-layout"><main className="aad-canvas"><div className="aad-canvas-label">Case data distributed to each agent · click a node to view its generated summary</div><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onNodeClick={onNodeClick} fitView fitViewOptions={{ padding: 0.15 }} minZoom={0.45} maxZoom={2} proOptions={{ hideAttribution: true }}><Background variant={BackgroundVariant.Dots} gap={20} size={1.5} color="#cbd5df" /><Controls showInteractive={false} /></ReactFlow><div className="aad-canvas-footer"><CheckCircle2 size={13} /> Agent result graph ready <span>Drag nodes · zoom canvas · click for summary</span></div></main><aside className="aad-detail">{selected ? <><div className="aad-detail-head"><div className="aad-detail-icon" style={{ background: selected.color }}><img src={selected.imageUrl} alt="" /></div><div><small>AGENT {selected.id} · COMPLETED</small><h2>{selected.name}</h2><span>{selected.domain}</span></div><button onClick={() => setSelected(null)}><X size={15} /></button></div><div className="aad-detail-section"><label>GENERATED SUMMARY</label><p className="aad-summary">{selected.findings[0]}</p></div><div className="aad-detail-section"><label>KEY FINDINGS</label>{selected.findings.map((finding) => <p className="aad-finding" key={finding}><CheckCircle2 size={13} />{finding}</p>)}</div><div className="aad-detail-section"><label>LINKED CASE DATA</label>{selected.links.map((link) => <div className="aad-link" key={link}><span><Network size={13} />{link}</span></div>)}</div><div className="aad-confidence"><span>CONFIDENCE</span><b>{selected.confidence}%</b><div><i style={{ width: `${selected.confidence}%` }} /></div></div></> : <div className="aad-empty"><Shield size={29} /><h2>Agent result details</h2><p>Select any agent card to view the summary generated from Case Data.</p></div>}<div className="aad-downloads"><label>DOWNLOAD AGENT SUMMARIES</label>{agentResults.map((agent) => <button key={agent.id} onClick={() => { setSelected(agent); downloadSummary(agent); }}><FileText size={13} /><span><b>Agent {agent.id}</b> · {agent.name}</span><Download size={13} /></button>)}</div></aside></div></section>;
}
